### ISSUE TITLE
Not seeing retrieved cover art.

### ISSUE THREAD

**Issue by Rbagman** [vanilla-music/vanilla-music-cover-fetch#1]
Android 4.4.2

The plugin pulls down the cover art, appears to save it, but the artwork doesn't show up. Also, I see different cover art in the album tab, but all in the tracks tab, reguardless of album/artist, have the same album cover.

**Comment by Kaned1as** [comment]
It's vanilla player issue, not cover fetch, sorry.
After _tags_ are updated, player does pick 'em up, but not after _artwork_ is updated.
I think it's related to album cover cache that player maintains.

Please create similar issue against [vanilla-music/vanilla](https://github.com/vanilla-music/vanilla) player itself.
