### ISSUE TITLE
Can't choose a folder to save a cover

### ISSUE THREAD

**Issue by steelman** [vanilla-music/vanilla-music-cover-fetch#10]
After successfully downloading and saving a one cover, I have got

> Nothing selected from SAF picker, exiting...

every time I have tried. The picker doesn't show up at all. Forcing restart of Vanilla Music doesn't help, neither do the restart of the plugin, nor even a reboot.

**Comment by Kaned1as** [comment]
What Android version do you have? Are you trying to save to external SD card? Have you by any chance missed the dialog with instructions on how to do this?

**Comment by steelman** [comment]
> What Android version do you have?

LineageOS 14.1 (Android 7.1.2)

> Are you trying to save to external SD card?

Yes, and I have succeeded onece.

> Have you by any chance missed the dialog with instructions on how to do this?

I saw it once (the first time I downloaded a cover after installing the plug-in) and followed the instructions. I've never seen it since then.

**Comment by Kaned1as** [comment]
Does the problem persist after reinstall?

**Comment by steelman** [comment]
Each time I uninstall and install the plug-in, I am asked for permision, shown the instructins (btw. they work but they aren't very cler) and I can write one cover. Then the problem is back.

**Comment by Kaned1as** [comment]
Will test it tomorrow, thanks for reporting

**Comment by Kaned1as** [comment]
Checked and it works. Can you record a video of you following the instructions?

**Comment by steelman** [comment]
[Here.](https://mstdn.io/@steelman/101369712534884759)

**Comment by Kaned1as** [comment]
You should select whole sdcard, not the folder with music. See steps 3, 4.

**Comment by steelman** [comment]
There is now such option. The only option in the menu ("Nowy folder") is "New folder". Then I choose ANDROID in the sidebar, which is my sdcard. And the file is saved properly.

**Comment by Kaned1as** [comment]
After you click ANDROID just click on "Select". This way you are granting access to the whole sdcard, not to one folder. See steps 3, 4.

**Comment by steelman** [comment]
😃 It works. Thank you. I am too tchnical to understand a few simple images.

**Comment by Kaned1as** [comment]
Maybe I should add another check too. Closing.

**Comment by Kaned1as** [comment]
Added in 6af5f164409c59448dbc3ed6b9b89b04b3e79e44, didn't test though.
