### ISSUE TITLE
Add changlog link to f-droid

### ISSUE THREAD

**Issue by Mannshoch** [vanilla-music/vanilla-music-cover-fetch#11]
please add the changelog as seen in the release as link to f-droid or into add it to readme.

**Comment by Kaned1as** [comment]
But it doesn't have distinct changelog, to be honest

**Comment by Kaned1as** [comment]
There aren't lots of features piling up into this project, it's mostly in maintenance mode. I upgrade it now and then to accomodate changes from newer versions of Android, that's all.

If you have a way to automatically create such a changelog from git commits, feel free to comment here.
