### ISSUE TITLE
Save cover image as folder.jpg

### ISSUE THREAD

**Issue by Papafelice** [vanilla-music/vanilla-music-cover-fetch#3]
Instead of putting the cover image into the tag of an individual file, the image could be stored as a separate folder.jpg file when a folder contains a set of songs from the same album.

(See also https://github.com/vanilla-music/vanilla/issues/546)

**Comment by Kaned1as** [comment]
Ok, no time for this this weekend, was dealing with tag editor issues.
Will do on next one.

**Comment by Kaned1as** [comment]
Turns out it's harder than I thought
It kinda works but only for usual files, some special snowflakes are not handled.

All my work that was done resides in [save-folder](https://github.com/vanilla-music/vanilla-music-cover-fetch/tree/save-folder) branch

**Comment by Kaned1as** [comment]
Done in 4e1ccbedac4337cf8a0e5bc49be05c6e9f9432eb

I can hand you apk file if you want.
Or you can wait till I fix remaining bugs and push the update to GPlay & F-Droid.
Feel free to comment.

**Comment by Papafelice** [comment]
Got the upgrade from fdroid, works nicely!

Thank you.

 

Gesendet: Dienstag, 30. Mai 2017 um 21:31 Uhr
Von: "Antic1tizen One" <notifications@github.com>
An: vanilla-music/vanilla-music-cover-fetch <vanilla-music-cover-fetch@noreply.github.com>
Cc: papafelice <felix.huber@schyf.de>, Author <author@noreply.github.com>
Betreff: Re: [vanilla-music/vanilla-music-cover-fetch] Save cover image as folder.jpg (#3)


Done in 4e1ccbe

I can hand you apk file if you want.
Or you can wait till I fix remaining bugs and push the update to GPlay & F-Droid.
Feel free to comment.
