### ISSUE TITLE
Add Art to Track from File

### ISSUE THREAD

**Issue by Allanitomwesh** [vanilla-music/vanilla-music-cover-fetch#4]
Hello,
I'd like to add a cover art to a song from one I already have on my phone. Could this functionality be added?

**Comment by Kaned1as** [comment]
Hmm, I think I'll take this on shortly

**Comment by Allanitomwesh** [comment]
Awesome

**Comment by Kaned1as** [comment]
Check it out on [build apk](https://github.com/vanilla-music/vanilla-music-cover-fetch/releases) or wait for F-Droid build 1.1.1 to happen (usually 2-3 days).

**Comment by Kaned1as** [comment]
Feel free to reopen if any concerns

**Comment by Allanitomwesh** [comment]
I get an error along the lines of "does not have permission to write to SD card"

**Comment by Kaned1as** [comment]
I'll check once I'm home.

Give it permission manually this time, via Application settings menu

**Comment by Allanitomwesh** [comment]
Works good now, combined with tag editor achieves effect
