### ISSUE TITLE
Choose a name to save the image as

### ISSUE THREAD

**Issue by steelman** [vanilla-music/vanilla-music-cover-fetch#9]
Enable users to choose the name of the image to be saved. Some may want folder.jpg (see #3, 4e1ccbe) others may prefer AlbumArt.jpg (vanilla-music/vanilla#692, vanilla-music/vanilla@8c49a074). Others may have their own preferences.

**Comment by Kaned1as** [comment]
Android metadata scanner respects only `folder.jpg` when scans for album art. That's why I don't plan on adding such a feature now. But will accept any PR implementing this.

**Comment by steelman** [comment]
> Android metadata scanner respects only folder.jpg when scans for album art.

I believe you are [wrong](https://android.googlesource.com/platform/packages/providers/MediaProvider/+/cbca3ba6ddcd9d693aa077251a683d4092a56c06/src/com/android/providers/media/MediaProvider.java#4295). Let the attached screenshots show the stock Music application and the folder with the album be the proof.

![screenshot_20190105-173920](https://user-images.githubusercontent.com/77683/50728087-e0d41100-1124-11e9-9175-8fba00e0df75.png)
![screenshot_20190105-174110](https://user-images.githubusercontent.com/77683/50728090-e893b580-1124-11e9-98fc-e8f3980a2b81.png)

**Comment by Kaned1as** [comment]
Done. Wait for next release.

**Comment by steelman** [comment]
Thank you.
